name: Build-Test

on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make deps-install
      - name: Run tests
        run: |
          pip install coverage pytest
          make test
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
      - name: Run lint
        run: |
          pip install black pycodestyle pylama pylint flake8 mypy pydocstyle vulture pytest
          sudo npm install -g pyright
          make lint
